---
title: "Primary Results"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
options("scipen" = 100, "digits" = 5)

options(warnPartialMatchAttr = FALSE,
        warnPartialMatchDollar = FALSE,
        warnPartialMatchArgs = FALSE)


library(tidyverse)
library(magrittr)
library(here)
library(deSolve)
library(flexsurv)
library(conflicted)
library(gt)
source(here("plot-theme.R"))
library(ggnewscale)
library(Matrix)
conflict_prefer("filter", "dplyr")
conflict_prefer("set_names", "magrittr")


source(here("common.R"))
source(here("simple-params.R"))
source(here("simple-des.R"))
source(here("simple-deq.R"))
source(here("simple-markov.R"))
source(here("simple-markov-corrected.R"))
source(here("simple-markov-corrected-monthly.R"))
source(here("simple-microsim.R"))
source(here("simple-microsim-corrected.R"))

```

## Model Parameters 

```{r parameter-table, echo = FALSE}
tbl <- 
  params %>% unlist() %>% data.frame() %>% 
  rownames_to_column() %>% 
  mutate(desc = as.character(params_lut[rowname])) %>% 
  select(3,1,2) %>% 
  mutate_at(vars(3),function(x) ifelse(x>1000,x/1000,ifelse(x<=1,round(x,3), round(x,1)))) %>% 
  #mutate(desc = gsub("$","\\$",desc)) %>% 
  set_colnames(c("Parameter Description","Short Name","Value")) #%>% 
  #tangram(., as.character=TRUE, style="lancet", caption="Model Parameters",id = "params")

tbl %>% 
  gt(rowname_col = "Parameter Description") %>% 
  tab_header(
    title = "Model Parameters"
  ) %>% 
  tab_options(
    table.width = pct(75)
  ) %>% 
  gtsave(filename = "figs/01_model-parameters.png")
tbl %>% write.csv("figs/02_model-parameters.csv")

```
## Base Case Results

```{r base-case-results, eval = TRUE, cache = FALSE}
params_orig <- params

convert_to_df <- function(df) df %>% as.data.frame() %>% rownames_to_column() %>% set_names(c("param","value")) %>% spread(param,value) %>% select(-contains("job"))
# Differntial Equations
icer_deq <- deq_icer(params)

# Embedded Markov 
params$interval = 1
icer_mar_corr_1y <- markov_corr_icer(params)
params$interval = 12
icer_mar_corr_1m <- markov_corr_m_icer(params)

# Uncorrected Markov 
params$interval = 1
icer_mar_1y <- markov_icer(params) 
params$interval = 12
icer_mar_1m <- markov_icer(params) 
params$interval = 365
icer_mar_1d <- markov_icer(params) 

# Discrete Event Simulation
icer_des <- des_icer(params,N = 1e7, seed = 123)

# Microsimulation 
# Due to high computation demand, our base case results for the microsimulatiob models were derived by 
# aggregating simulations with small cohort size (1k individuals).
# Please refer to parallel_microsim.R for a mini example of how we iterate the simulation and scale it up.
# Or directly load the results.
micro_r <- read.csv(here("data/microsim_results.csv"),stringsAsFactors = FALSE,row.names = NULL) 
cn <- c("dCOST.ref","dCOST.test","dQALY.ref","dQALY.test","ICER","NMB")
icer_micro_y <- micro_r[micro_r$model=="micro_y",] %>% select_at(cn)
icer_micro_d <- micro_r[micro_r$model=="micro_d",] %>% select_at(cn)
icer_micro_corr_y <- micro_r[micro_r$model=="micro_corr_y",] %>% select_at(cn)
icer_micro_corr_m <- micro_r[micro_r$model=="micro_corr_m",] %>% select_at(cn)


result <-
  list("DEQ" = convert_to_df(icer_deq), 
       "MARKOV_DAY" = convert_to_df(icer_mar_1d),
       "MARKOV_MON" = convert_to_df(icer_mar_1m),
       "MARKOV_YR" = convert_to_df(icer_mar_1y),
       "MARKOV_EMB_MON" = convert_to_df(icer_mar_corr_1m),
       "MARKOV_EMB_YR" = convert_to_df(icer_mar_corr_1y),
       "DES" = convert_to_df(icer_des),
       "MICRO_DAY" = icer_micro_d,
       "MICRO_YR" = icer_micro_y,
       "MICRO_CORR_YR" = icer_micro_corr_y,
       "MICRO_CORR_MON" = icer_micro_corr_m)

base_case_result <- 
  result %>% 
    bind_rows(.id = "model") %>% 
    select(model,ICER,NMB, everything()) %>% 
    gather(output, value, -model) %>% 
    tbl_df() %>% 
    separate(col = output,into=c("output","strategy"))  

names(result)
lbl_m <- c(
                          "Differential Equations",
                          "Markov Cohort - Daily Cycle","Markov Cohort - Monthly Cycle","Markov Cohort - Yearly Cycle",
                          #"Embedded Markov Cohort - Daily Cycle",
                          "Embedded Markov Cohort - Monthly Cycle",
                          "Embedded Markov Cohort - Yearly Cycle",
                          "Discrete Event Simulation",
                          "Microsimulation - Daily Cycle","Microsimulation - Yearly Cycle",
                          "Embedded Microsimulation - Yearly Cycle","Embedded Microsimulation - Monthly Cycle"
                        )

t1 <- base_case_result %>% #NMB & ICER
          filter(is.na(strategy)) %>% 
        mutate(output = factor(output,levels = c("dQALY","dCOST","ICER","NMB"), 
                               labels = c("Mean QALYs","Mean Costs","ICER","Net Monetary Benefit"))) %>% 
          mutate(model = factor(model, levels = names(result), 
                        labels = lbl_m)) %>% 
        select(model,output,incremental=value)

t2 <- base_case_result %>% #discounted cost/QALY/diff
  filter(!is.na(strategy)) %>% 
  spread(strategy,value) %>% 
  mutate(output = factor(output,levels = c("dQALY","dCOST"), 
                         labels = c("Mean QALYs","Mean Costs"))) %>% 
  mutate(model = factor(model, levels = names(result), 
                        labels = lbl_m)) %>% 
  arrange(output,model) %>% 
  select(output,model,ref,test) %>% 
  mutate(incremental = test - ref) 

table_main_results <- bind_rows(t1,t2) %>% 
  mutate_at(vars(ref,test,incremental),function(x) ifelse(abs(x)<100,round(x,3),round(x,0))) %>%  
  mutate(output = ifelse(model == "Differential Equations",output, "")) %>% 
  mutate_all(funs(as.character)) %>% 
  mutate_at(vars(ref,test), function(x) ifelse(is.na(x) | x=="NA", "",x)) %>% 
  select(output,model,ref,test,incremental) %>% 
  set_colnames(c("Outcome","Model Type","No Testing (ref.)","Genetic Testing","Incremental")) #%>% 
  #tangram(., style= "Hmisc", caption="Base Case Results",id = "base_case")

table_main_results %>% 
  write.csv(here("output/icer-results.csv"))


table_main_results[,-1] %>% 
  gt(rowname_col = "Model Type") %>% 
  tab_row_group(rows = 1:11, group = "ICER") %>% 
  tab_row_group(rows = 12:22, group = "Net Monetary Benefit (NMB)") %>% 
  tab_row_group(rows = 23:33, group = "Mean QALYs") %>% 
  tab_row_group(rows = 34:44, group = "Mean Costs") %>% 
  tab_footnote(footnote = "QALY = Quality-Adjusted Life Years", cells_group("Mean QALYs")) %>% 
  tab_footnote(footnote = "ICER = Incremental Cost-Effectiveness Ratio", cells_group("ICER")) %>% 
  #tab_footnote(footnote = "Willingness to Pay = $100,000 per QALY",cells_group("Net Monetary Benefit")) %>% 
  #tab_source_note(source_note = "Source: Source") %>% 
  #tab_source_note(source_note = "Note: Another note")  %>% 
  tab_options(
    table.width = pct(75)
  ) %>% 
  gtsave(filename = here("figs/01_main-results.png"))
  
```

## Examine Stochasticity

```{r model_convergence}
#### Model Iteration Results ####
# Model results without stochasticity: DEQ, Markov
icer_deq
icer_mar_1y
icer_mar_corr_1y

# Model results with stochasticity: DES, Microsim
# Each model was run 1k times for each N in our study. 
# Please refer to iterate_des_microsim.R for a mini example of how we generate our results
# Or directly load the results.
icer_1k <- read.csv(here("data/icer_des_micro_1k.csv"),stringsAsFactors = FALSE,row.names = NULL) 
icer_des_1k <- icer_1k[icer_1k$name=="icer_des_1k",]
icer_micro_d_1k <- icer_1k[icer_1k$name=="icer_micro_d_1k",]
icer_micro_y_1k <- icer_1k[icer_1k$name=="icer_micro_y_1k",]
icer_micro_corr_y_1k <- icer_1k[icer_1k$name=="icer_micro_corr_y_1k",]
icer_micro_corr_m_1k <- icer_1k[icer_1k$name=="icer_micro_corr_m_1k",]

####Convergence Box Plots####
lines <- data.frame(model=c("DEQ","MARKOV","MARKOV-EMB"),
                    NMB=c(icer_deq["NMB"],icer_mar_1y["NMB"],icer_mar_corr_1y["NMB"]),stringsAsFactors = F) %>% 
  mutate(timestep=model)

dots <-   icer_des_1k %>% mutate(model="DES") %>% 
    bind_rows(icer_micro_y_1k %>% mutate(model="Microsim Yearly")) %>% 
    bind_rows(icer_micro_d_1k %>% mutate(model="Microsim Daily")) %>% 
    bind_rows(icer_micro_corr_y_1k %>% mutate(model="Microsim Yearly Corrected")) %>% 
    bind_rows(icer_micro_corr_m_1k %>% mutate(model="Microsim Monthly Corrected")) %>% 
    group_by(model,N) %>% slice(1) %>% summarise(NMB=mean(NMB))

icer_micro_d_1k$timestep <- "MICROSIM-D"
icer_micro_y_1k$timestep <- "MICROSIM-Y"
icer_micro_corr_y_1k$timestep <- "MICROSIM-EMB-Y"
icer_micro_corr_m_1k$timestep <- "MICROSIM-EMB-M"
icer_des_1k$timestep <- "DES"

micro <- bind_rows(icer_micro_d_1k, icer_micro_y_1k,icer_micro_corr_y_1k,icer_micro_corr_m_1k,
                   icer_des_1k[,c("NMB", "N", "seed", "iteration", "timestep")]) 
micro$logN <- factor(round(log10(micro$N)))

tiff("./figs/Micro Simulation Convergence.tiff",res=300,units="in",width=6.5, height=5)

ggplot(micro, aes(x=logN,y=NMB,color=timestep,fill=timestep),alpha=0.7) +
    geom_boxplot(coef=1e30) +
    scale_color_manual(name="",values = c("grey40","orange2","red3","blue","black")) +
    scale_fill_manual(name="",values = c("grey80","gold1","tomato","skyblue","khaki4")) +
    new_scale_color() +
    geom_hline(data=ll,aes(yintercept=NMB,color=timestep,linetype=timestep)) + 
    scale_linetype_manual(name="",values=c("solid","dashed","dotdash")) + 
    scale_color_manual(name="",values = c("black","darkgreen","purple")) + 
    scale_size_manual(name="",values = c(0.5,0.5,0.8)) +
    xlab("Number of Simulated Patients\n(log)") + 
    theme_bw() +
    theme(panel.grid.minor.y=element_blank())

dev.off()


```

## Model Run Time

```{r microbenchmark}
### We ran each model 100 times using microbenchmark on ACCRE.###
# Please refer to compare_runtime.R for a mini example of how we generate our results
# Or directly load the results.
# For stochastic models (DES/microsimulation), we ran at sample size of 10 million individuals.
rt <- read.csv(here("data/runtime.csv"),stringsAsFactors = FALSE,row.names = NULL)
b_deq <- rt[rt$name == "b_deq", ]
b_des <- rt[rt$name == "b_des", ]
b_mark_y <- rt[rt$name == "b_mark_y", ]
b_mark_m <- rt[rt$name == "b_mark_m", ]
b_mark_d <- rt[rt$name == "b_mark_d", ]
b_mark_corr_y <- rt[rt$name == "b_mark_corr_y", ]
b_mark_corr_m <- rt[rt$name == "b_mark_corr_m", ]
b_micro_y <- rt[rt$name == "b_micro_y", ]
b_micro_corr_y <- rt[rt$name == "b_micro_corr_y", ]

runtimes <- b_deq %>% mutate(model="DEQ") %>% 
    bind_rows(b_des %>% mutate(model="DES (10mil)")) %>% 
    bind_rows(b_mark_y %>% mutate(model="MARKOV-Y")) %>% 
    bind_rows(b_mark_m %>% mutate(model="MARKOV-M")) %>% 
    bind_rows(b_mark_d %>% mutate(model="MARKOV-D")) %>% 
    bind_rows(b_mark_corr_y %>% mutate(model="MARKOV-EMB-Y")) %>% 
    bind_rows(b_mark_corr_m %>% mutate(model="MARKOV-EMB-M")) %>%     
    bind_rows(b_micro_y %>% mutate(model="MICROSIM-Y (10 mil)")) %>% 
    bind_rows(b_micro_corr_y %>% mutate(model="MICROSIM-EMB-Y (10 mil)")) %>% 
    mutate(times=time/10^9)
    
tiff("./figs/Runtime Comparison.tiff",res=300,units="in",width=6, height=5)
ggplot(runtimes) +
    geom_boxplot(aes(x=model,y=times),outlier.shape = 1,outlier.alpha = 0.5) +
    scale_y_continuous(breaks = 10^seq(-3,4,0.5), labels = seq(-3,4,0.5), trans="log10") + ylab("log10(seconds)") + xlab("Method") +
    coord_flip() + theme_bw() +
    theme(panel.grid.major.y=element_blank())
dev.off()

```
